version: '3.9'
services:
  app:
    container_name: app_magento2
    hostname: app
    image: koderlab/php-fpm:8.3-bookworm
    env_file:
      - ./config/.env
    volumes:
      - ./magento:/var/www/html
      - ./config/docker-entrypoint-initphp.d/setup.sh:/docker-entrypoint-initphp.d/setup.sh
      - ./config/docker-entrypoint-initphp.d/extras/:/docker-entrypoint-initphp.d/extras/
      - ./config/usr/local/bin/redis-cli:/usr/local/bin/redis-cli
      - ./config/php-settings/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-settings/usr/local/etc/php/conf.d/docker-php-ext-mailhog.ini:/usr/local/etc/php/conf.d/docker-php-ext-mailhog.ini
      - phpfpmsocket:/var/run/php-fpm
    depends_on:
      - mysql
      - elasticsearch
      - redis
    networks:
      - magento2-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    container_name: web_magento2
    hostname: web
    image: nginx:stable-alpine
    env_file:
      - ./config/.env
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/magento/magento2.conf:/etc/nginx/magento/magento2.conf
      - ./config/nginx/magento/ssl.conf:/etc/nginx/magento/ssl.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./magento:/var/www/html
      - ./config/nginx/502.html:/var/www/html/502.html
      - phpfpmsocket:/var/run/php-fpm
    depends_on:
      app:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    networks:
      - magento2-network

  mysql:
    container_name: mysql_magento2
    hostname: mysql
    image: mariadb:10.4
    env_file:
      - ./config/env/db/.env
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"
    networks:
      - magento2-network

  redis:
    container_name: redis_magento2
    hostname: redis
    image: redis:6.2
    env_file:
      - ./config/env/redis/.env
    ports:
      - "6379:6379"
    networks:
      - magento2-network

  rabbitmq:
    container_name: rabbitmq_magento2
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magento2-network

  elasticsearch:
    container_name: elastic_magento2
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - node.name=elasticv2
    volumes:
      - elasticdata:/var/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - magento2-network

  mailhog:
    container_name: mailhog_magento2
    hostname: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento2-network

volumes:
  phpfpmsocket:
  elasticdata:
    driver: local

networks:
    magento2-network:
      driver: bridge
